//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string customer_id { get; set; }
        public string price { get; set; }
        public string status { get; set; }
    
        public virtual orderdetail orderdetail { get; set; }
    }
}
