//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual product products1 { get; set; }
        public virtual product product1 { get; set; }
    }
}
